### ISSUE TITLE
Issue with SpamCheck API :

### ISSUE THREAD

**Issue by srishti-dev** [smoak/postmark-spamcheck#3]
Hi , 
I am getting CORS error in Spam check API .
Could you let me know what changes you mage to not get CORS error.

**Comment by smoak** [comment]
Can you be more specific than that? What are you attempting to do? What code are you running? etc.

**Comment by srishti-dev** [comment]
Hi , I am using the same API `https://spamcheck.postmarkapp.com/filter`  , but instead of using it through C# i am using through node server .
And using this API always provide me with same response and rules mentioned out to be i have not passed headers as To , From , SUbject .
I am sharing the payload . could you please share your payload . so i am able to use it .

PAYLOAD : {email : `To: gupta.srishti@thinksys.com
      From: abv@gmail.com
      Subject: campaign test
      <html>
      campaign content to be shared</html>`}

**Comment by smoak** [comment]
This is not an issue related to this C# library. I am not the owner/creator of that spamcheck API. This repo is a library written in C# to allow easier access to that spamcheck API. The API documentation is provided by [Postmark](https://postmarkapp.com/) which you can access [here](https://spamcheck.postmarkapp.com/doc/). Closing this as it is not a specific issue related to this codebase/library.
